# Generated by Django 4.2.4 on 2023-08-17 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='articulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_articulo', models.CharField(max_length=500, unique=True, verbose_name='campo id autor')),
                ('titulo_del_articulo', models.CharField(max_length=500, verbose_name='titulo del articulo')),
                ('fecsys', models.DateTimeField(auto_now_add=True, max_length=500, verbose_name='fecha del articulo')),
            ],
        ),
        migrations.CreateModel(
            name='autores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_autor', models.CharField(max_length=500, unique=True, verbose_name='campo id autor')),
                ('nombre_autor', models.CharField(max_length=500, verbose_name='nombre del autor')),
                ('afiliacion_autor', models.CharField(max_length=500, verbose_name='nombre de la afiliacion A')),
            ],
        ),
        migrations.CreateModel(
            name='revista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_revista', models.CharField(max_length=500, unique=True, verbose_name='campo id autor')),
                ('nombre_revista', models.CharField(max_length=500, verbose_name='nombre de la revista ')),
                ('issn1', models.CharField(max_length=500, verbose_name='cedula revista #1')),
                ('issn2', models.CharField(max_length=500, verbose_name='cedula revista #2')),
                ('issn3', models.CharField(max_length=500, verbose_name='cedula revista #3')),
                ('issn4', models.CharField(max_length=500, verbose_name='cedula revista #4')),
                ('cuartil', models.CharField(max_length=500, verbose_name='cedula revista #4')),
                ('ciudad', models.CharField(max_length=500, verbose_name='ciudad')),
                ('region', models.CharField(max_length=500, verbose_name='region')),
                ('publicador', models.CharField(max_length=500, verbose_name='publicador')),
            ],
        ),
        migrations.CreateModel(
            name='autores_articulos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_autor_articulo', models.CharField(max_length=500, unique=True, verbose_name='id autor del articulo')),
                ('id_articulo_A', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.articulo')),
                ('id_autor_A', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.autores')),
            ],
        ),
        migrations.AddField(
            model_name='articulo',
            name='id_revista_articulo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.revista'),
        ),
    ]
