# Generated by Django 4.2.4 on 2023-08-17 21:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('ciudad', models.CharField(max_length=100)),
                ('fecha_creacion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='libro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_libro', models.CharField(max_length=100)),
                ('tema', models.CharField(max_length=100)),
                ('fecha', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='auto_libr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_auto_libr', models.CharField(max_length=100)),
                ('id1_dlibro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.libro')),
                ('id2_autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.autor')),
            ],
        ),
    ]
